version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'site_data:/var/www/html'
      - /data/gameculturegamification/moodledata:/var/www/moodledata
    depends_on:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10

  mysql:
    image: 'mysql:8'
    ports:
      - "127.0.0.1:5436:3306"
    volumes:
      - /data/gameculturegamification/db_data/db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_ROOT}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${SERVICE_USER_MOODLE}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_MOODLE}
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - 127.0.0.1
      interval: 5s
      timeout: 20s
      retries: 10
