version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./site_data:/var/www/html
      - ./moodledata:/var/www/moodledata
    depends_on:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10

  mysql:
    image: 'mysql:8'
    restart: always
#    ports:
#      - "127.0.0.1:5436:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_ROOT}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${SERVICE_USER_MOODLE}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_MOODLE}
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - 127.0.0.1
      interval: 5s
      timeout: 20s
      retries: 10

  redis:
    image: 'redis:alpine'
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    command: redis-server --appendonly yes